version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - apt-get update -qq
      - apt-get install -y ffmpeg python3-pip
      - pip3 install --upgrade pip
      - pip3 install yt-dlp

  pre_build:
    commands:
      - echo "Build started on `date`"
      - echo "Preparing download..."

  build:
    commands:
      - echo "Starting YouTube download..."
      - mkdir -p downloads
      - |
        cat > download.py << 'EOF'
        import yt_dlp
        import os
        
        CHANNEL_URL = os.environ.get('CHANNEL_URL', 'https://www.youtube.com/@MrBeast')
        
        ydl_opts = {
            'outtmpl': 'downloads/%(title)s.%(ext)s',
            'format': 'best[ext=mp4]/best',
            'quiet': False,
            'playlistend': 3
        }
        
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            print(f"Downloading from: {CHANNEL_URL}")
            ydl.download([CHANNEL_URL])
        
        print("Download completed!")
        EOF
      - python3 download.py
      - ls -la downloads/

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Listing downloaded files:"
      - ls -la downloads/ || echo "No files"

artifacts:
  files:
    - 'downloads/**/*'
